#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false

# Disable password authentication fo root user
ssh_pwauth: false

# Install required packages
packages:
  - yum-utils

# Install Docker + Docker Compose & Start Docker
runcmd:
  - sudo yum install puppet-agent
  - puppet config set server 78.46.217.145 --section main
  - sudo puppet ssl bootstrap
#  - puppetserver -v



  # - curl -L "https://github.com/docker/compose/releases/download/${docker_compose_version}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  # #- curl -fsSL https://raw.githubusercontent.com/MatchbookLab/local-persist/master/scripts/install.sh | bash
  # - chmod +x /usr/local/bin/docker-compose
  # - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  # - yum install -y docker-ce docker-ce-cli containerd.io
  # - sed -i -e "s|ExecStart=/usr/bin/dockerd|ExecStart=/usr/bin/dockerd --data-root=/mnt/docker_data_volume|g" /lib/systemd/system/docker.service
  # - systemctl daemon-reload
  # - systemctl restart docker
  # - systemctl enable docker
  # - docker swarm init
