#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false

# Disable password authentication fo root user
ssh_pwauth: false

# Install required packages
packages:
  - yum-utils

# 
runcmd:
  - sudo wget https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
  - sudo rpm -Uvh mysql80-community-release-el7-3.noarch.rpm
  - sudo yum install -y mysql-server
  - sudo systemctl start mysqld
  - sudo systemctl status mysqld
  - sudo grep 'password' /var/log/mysqld.log